# Default values for tenant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# kubeconfig: /home/iguazio/.kube/config

scaler:
  image:
    repository: pavelrigz/scaler
    tag: 1.0.0
    pullPolicy: Always
  
  config:
    command: ./autoscaler
  
  args:
    scaleInterval: 2m
    scaleWindow: 1m
    metricsPollInterval: 10s
    metricName: num_of_requests
    metricsGroupKind: Deployment
    scaleThreshold: 0

general:
  config:
    pathMount: /home/app_resourcescaler

dlx:
  image:
    repository: pavelrigz/dlx
    tag: 1.0.0
    pullPolicy: Always
  
  config:
    command: ./dlx

  args:
    targetNameHeader: X-App-Target
    targetPathHeader: ""
    targetPort: 8080
    listenAddress: :8080

nodeSelector: {}

tolerations: []

affinity: {}
