apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scaler.dlx.name" . }}
  labels:
    app: {{ template "scaler.name" . }}
    chart: {{ template "scaler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: dlx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "scaler.name" . }}
      chart: {{ template "scaler.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: dlx
  template:
    metadata:
      labels:
        app: {{ template "scaler.name" . }}
        chart: {{ template "scaler.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: dlx
    spec:
      containers:
        - name: dlx
          image: {{ .Values.dlx.image.repository }}:{{ .Values.dlx.image.tag }}
          imagePullPolicy: {{ .Values.dlx.image.pullPolicy }}
          workingDir: "{{ .Values.general.config.pathMount }}"
          command: ["{{ .Values.dlx.config.command }}"]
          env:
            - name: SCALER_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KUBECONFIG
              value: ""
          args:
            - --namespace={{ .Release.Namespace }}
            - --target-name-header={{ .Values.dlx.args.targetNameHeader }}
            - --target-path-header={{ .Values.dlx.args.targetPathHeader }}
            - --target-port={{ .Values.dlx.args.targetPort }}
            - --listen-address={{ .Values.dlx.args.listenAddress }}
