apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scaler.scaler.name" . }}
  labels:
    app: {{ template "scaler.name" . }}
    chart: {{ template "scaler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "scaler.name" . }}
      chart: {{ template "scaler.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: scaler
  template:
    metadata:
      labels:
        app: {{ template "scaler.name" . }}
        chart: {{ template "scaler.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: scaler
    spec:
      containers:
        - name: scaler
          image: {{ .Values.scaler.image.repository }}:{{ .Values.scaler.image.tag }}
          imagePullPolicy: {{ .Values.scaler.image.pullPolicy }}
          workingDir: "{{ .Values.general.config.pathMount }}"
          command: ["{{ .Values.scaler.config.command }}"]
          env:
            - name: SCALER_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KUBECONFIG
              value: ""
          args:
            - --namespace={{ .Release.Namespace }}
            - --scale-interval={{ .Values.scaler.args.scaleInterval }}
            - --scale-window={{ .Values.scaler.args.scaleWindow }}
            - --metrics-poll-interval={{ .Values.scaler.args.metricsPollInterval }}
            - --metric-name={{ .Values.scaler.args.metricName }}
            - --metrics-group-kind={{ .Values.scaler.args.metricsGroupKind }}
            - --scale-threshold={{ .Values.scaler.args.scaleThreshold }}
