apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scaler.scaler.name" . }}
  labels:
    app: {{ template "scaler.name" . }}
    chart: {{ template "scaler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "scaler.name" . }}
      chart: {{ template "scaler.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: scaler
  template:
    metadata:
      labels:
        app: {{ template "scaler.name" . }}
        chart: {{ template "scaler.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: scaler
    spec:
      containers:
      - name: scaler
        image: {{ .Values.scaler.image.repository }}:{{ .Values.scaler.image.tag }}
        imagePullPolicy: {{ .Values.scaler.image.pullPolicy }}
        env:
        - name: SCALER_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: KUBECONFIG
          value: {{ .Values.kubeconfig }}
        args:
        # - --namespace={{ .Release.Namespace }}
        - --scale-interval={{ .Values.scaler.scale_interval }}
        - --scale-window={{ .Values.scaler.scale_window }}
        - --metrics-poll-interval={{ .Values.scaler.metrics_poll_interval }}
        - --metric-name={{ .Values.scaler.metric_name }}
        - --scale-threshold={{ .Values.scaler.scale_threshold }}
