apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metrics-server-exporter.name" . }}
  labels:
    app: {{ template "metrics-server-exporter.name" . }}
    chart: {{ template "metrics-server-exporter.chart" . }}
    release: {{ .Release.Name }}
