apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: metrics-server-exporter
subjects:
- kind: ServiceAccount
  name: metrics-server-exporter
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
