apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: "{{ .Values.container.path }}"
    prometheus.io/port: "{{ .Values.container.port }}"
    prometheus.io/scrape: "true"
  name: metrics-server-exporter
  labels:
    app: {{ template "metrics-server-exporter.name" . }}
    chart: {{ template "metrics-server-exporter.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.container.port }}
  selector:
    app: metrics-server-exporter
